FROM python:latest

COPY flag.txt /flag.txt

RUN apt-get update && apt-get install -y python3-pip

RUN pip3 install --upgrade pip

RUN mkdir -p /app

WORKDIR /app

COPY main.py /app/

COPY requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

EXPOSE 1337

CMD [ "python3", "main.py" ]
